"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import "../public/css/bootstrap.css";
// --- tabaultor css ---
// import "react-tabulator/lib/styles.css";
// import 'bootstrap/dist/css/bootstrap.css'
// import 'bootstrap-icons/font/bootstrap-icons.css'
import HeaderBar from "./components/nav/HeaderNav";
import NavBar from "./components/nav/Navbar";
import Script from "next/script";
import { usePathname } from "next/navigation";
import LoginPage from "@/constant/loginPage";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isLogin = usePathname();
  console.log(isLogin);
  const isLoginStatus = isLogin === "/login";
  console.log(isLoginStatus);

  useEffect(() => {
    if (isLoginStatus) {
      document.body.style.backgroundColor = "#000";
    } else {
      document.body.style.backgroundColor = "";
    }

    // 컴포넌트가 언마운트될 때 스타일 초기화
    return () => {
      document.body.style.backgroundColor = "";
    };
  }, [isLoginStatus]);

  return (
    <html lang="en">
      <body>
        {!isLoginStatus ? (
          <header>
            <HeaderBar />
          </header>
        ) : (
          <div></div>
        )}
        <main>
          {!isLoginStatus ? <NavBar /> : <div></div>}

          {/* <NavBar /> */}
          {/* <div className="content">{children}</div> */}
          {!isLoginStatus ? (
            <div className="content">{children}</div>
          ) : (
            <div className="">{children}</div>
          )}

          <Script src="/js/nav2.js" strategy="beforeInteractive"></Script>
        </main>
      </body>
    </html>
  );
}
