import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '../app/assets/scss/themes.scss';
import NavBar from './components/nav/Navbar'
import { Providers } from '@/redux/provider';
import fakeBackend from './monitoring/helpers/fakeBackend';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <Providers>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  )
}

