import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Footer from './layouts/Footer'
import React from 'react'
import { Col, Row } from 'reactstrap'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function MonitoringLayout(props: {
    children: React.ReactNode
    system: React.ReactNode
    mlsn: React.ReactNode
}) {
    return (
        <React.Fragment>
            <div id="layout-wrapper">
                {props.children}
                {/* {props.mlsn} */}
                {props.system}
                <Footer />
            </div>
        </React.Fragment>
    )
}