import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Footer from './layouts/Footer'
import React from 'react'
import { Col, Container, Row } from 'reactstrap'
import MonitorHeader from './monitorHeader'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function MonitoringLayout(props: {
    children: React.ReactNode
    system: React.ReactNode
    mlsn: React.ReactNode
}) {
    return (
        <React.Fragment>
            <div id="layout-wrapper">
                <Container fluid>
                    <Row className='mb-1'>
                        <MonitorHeader title="EMAMS" pageTitle="Monitoring" />
                    </Row>
                    <Row>
                        <Col lg={12}>
                            {props.children}
                        </Col>
                    </Row>
                    <Row>
                        <Col lg={8} className='p-0'>
                            {props.system}
                        </Col>
                        <Col lg={4} className='p-0'>
                            {props.mlsn}
                        </Col>
                    </Row>
                </Container>
                <Footer />
            </div>
        </React.Fragment>
    )
}