import type { Metadata } from 'next'
import MonitorFooter from './layouts/monitorFooter'
import React from 'react'
import { Col, Container, Row } from 'reactstrap'
import { MonitorHeader } from './layouts/monitorHeader'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function MonitoringLayout(props: {
    children: React.ReactNode
}) {
    return (
        <React.Fragment>
            <div id="layout-wrapper">
                <Container fluid>
                    <Row className='mb-1'>
                        <MonitorHeader/>
                    </Row>
                    <Row>
                        <Col lg={12}>
                            {props.children}
                        </Col>
                    </Row>
                    <MonitorFooter />
                </Container>
            </div>
        </React.Fragment>
    )
}