import type { Metadata } from 'next'
import React from 'react'
import './styles/monitoring.css'
import MonitorFooter from './layouts/monitorFooter'
import { MonitorHeader } from './layouts/monitorHeader'

export const metadata: Metadata = {
  title: 'Monitor',
  description: 'Generated by create next app',
}

export default function MonitoringLayout(props: {
    children: React.ReactNode
}) {
    return (
        <React.Fragment>
            <div id='monitor-wrapper' className='overflow-y-auto overflow-x-hidden'>
                <div className='monitor-wrap'>
                    <div className='monitor-top'>
                        <MonitorHeader />
                    </div>
                    <div className='monitor-body'>
                        <div className='content__boxed'>
                            {props.children}
                        </div>
                    </div>
                    <div className='monitor-footer'>
                    <MonitorFooter />
                    </div>
                </div>
            </div>
        </React.Fragment>
    )
}